image: "maven:3-jdk-8-slim"

variables:
  MAVEN_CLI_OPTS: "-fae --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: portent
  paths:
    - .m2/repository/

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify
  artifacts:
    paths:
      - "**/target/apidocs"
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"
        - "**/target/failsafe-reports/TEST-*.xml"